import puppeteer from 'puppeteer';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

// Get __dirname in ES module
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ===============================
// ✅ Consultation Report PDF
// ===============================
export const generateConsultationReport = async ({
  patientName,
  doctorName,
  consultationId,
  scheduledTime,
  consultationType,
  status,
  diagnosis,
  treatment,
  notes,
}) => {
  const logoPath = path.resolve(__dirname, '../../assets/logo.png');
  const logoBase64 = fs.readFileSync(logoPath, { encoding: 'base64' });
  const logoDataUri = `data:image/png;base64,${logoBase64}`;

  const htmlContent = `
  <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { display: flex; align-items: center; margin-bottom: 30px; }
        .logo { width: 110px; }
        .title { flex: 1; text-align: right; font-size: 24px; font-weight: bold; color: #2E86C1; }

        .section { margin-bottom: 20px; }
        .section-title { font-size: 18px; font-weight: bold; color: #2C3E50; margin-bottom: 8px; }
        .row p { margin: 4px 0; font-size: 15px; }

        .box {
          background: #F9F9F9;
          padding: 15px;
          border-radius: 6px;
          border-left: 4px solid #2E86C1;
        }

        .footer {
          margin-top: 40px;
          text-align: center;
          font-size: 13px;
          color: #777;
        }

        .divider {
          border-bottom: 2px solid #eee;
          margin: 25px 0;
        }
      </style>
    </head>

    <body>
      <div class="header">
        <img src="${logoDataUri}" class="logo" />
        <div class="title">Consultation Report</div>
      </div>

      <div class="section row">
        <p><strong>Consultation ID:</strong> #${consultationId}</p>
        <p><strong>Date & Time:</strong> ${scheduledTime}</p>
        <p><strong>Status:</strong> ${status}</p>
        <p><strong>Type:</strong> ${consultationType}</p>
      </div>

      <div class="divider"></div>

      <div class="section row">
        <p><strong>Patient Name:</strong> ${patientName}</p>
        <p><strong>Doctor Name:</strong> ${doctorName}</p>
      </div>

      <div class="divider"></div>

      <div class="section">
        <div class="section-title">Diagnosis</div>
        <div class="box">${diagnosis || '—'}</div>
      </div>

      <div class="section">
        <div class="section-title">Treatment Plan</div>
        <div class="box">${treatment || '—'}</div>
      </div>

      <div class="section">
        <div class="section-title">Additional Notes</div>
        <div class="box">${notes || '—'}</div>
      </div>

      <div class="footer">
        Generated by HealthPal<br/>
        https://healthpal.example.com
      </div>
    </body>
  </html>
  `;

  const browser = await puppeteer.launch({
    args: ['--no-sandbox'],
    headless: true,
  });

  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

  const pdfPath = path.resolve(`reports/consultation-${consultationId}.pdf`);
  fs.mkdirSync(path.dirname(pdfPath), { recursive: true });

  await page.pdf({
    path: pdfPath,
    format: 'A4',
    printBackground: true,
  });

  await browser.close();
  return pdfPath;
};

export const generateDonationInvoice = async ({ donorName, caseTitle, amount, date }) => {
  // Logo setup
  const logoPath = path.resolve(__dirname, '../../assets/logo.png');
  const logoBase64 = fs.readFileSync(logoPath, { encoding: 'base64' });
  const logoDataUri = `data:image/png;base64,${logoBase64}`;

  const htmlContent = `
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          .header { display: flex; align-items: center; margin-bottom: 40px; }
          .logo { width: 120px; }
          .title { flex: 1; text-align: right; font-size: 24px; font-weight: bold; color: #2E86C1; }
          .invoice-details { margin-bottom: 30px; }
          .invoice-details p { margin: 4px 0; font-size: 16px; }
          .amount { font-size: 20px; font-weight: bold; color: #27AE60; margin-top: 20px; }
          .footer { margin-top: 50px; text-align: center; font-size: 14px; color: #555; }
          .divider { border-bottom: 2px solid #eee; margin: 20px 0; }
        </style>
      </head>
      <body>
        <div class="header">
          <img src="${logoDataUri}" class="logo" />
          <div class="title">Donation Invoice</div>
        </div>
        <div class="invoice-details">
          <p><strong>Donor Name:</strong> ${donorName}</p>
          <p><strong>Case Title:</strong> ${caseTitle}</p>
          <p><strong>Date:</strong> ${date}</p>
          <p class="amount">Amount Donated: $${amount}</p>
        </div>
        <div class="divider"></div>
        <div class="footer">
          Thank you for supporting Health Pal!<br/>
          Visit us at <a href="https://healthpal.example.com">healthpal.example.com</a>
        </div>
      </body>
    </html>
  `;

  const browser = await puppeteer.launch({ args: ['--no-sandbox'], headless: true });
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

  // Save PDF
  const pdfPath = path.resolve(`invoices/invoice-${Date.now()}.pdf`);
  fs.mkdirSync(path.dirname(pdfPath), { recursive: true });
  await page.pdf({ path: pdfPath, format: 'A4', printBackground: true });

  await browser.close();
  return pdfPath;
};
